version: "3.3"

services:
  
  bot:
    networks: ['mynetwork']
    build: ./bot
    volumes:
      - ./bot:/app
    depends_on:
      postgres:
        condition: service_healthy
    stdin_open: true
    tty: true
    restart: always
    environment:
      - TG_TOKEN
      - PG_PASS

  postgres:
    image: "postgres"
    networks: ['mynetwork']

    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 5s
      retries: 5

    environment:
      POSTGRES_PASSWORD: $PG_PASS

    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432 

    restart: always

    stdin_open: true
    tty: true

  postgres-setup:
    networks: ['mynetwork']
    environment:
      POSTGRES_PASSWORD: $PG_PASS

    build: ./postgres
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"
  


networks: {
  mynetwork: {}
}

