name: "js tests"


on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
        neo4j:
            image: neo4j:latest
            ports:
                - 7474:7474
                - 7687:7687
            env:
                NEO4J_AUTH: neo4j/password


    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19.x'

      - name: Install dependencies
        run: yarn

      - run: cp .env.example .env


      - name: Run tests
        run: yarn run jest test/all.test.ts
