name: "js tests"


on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    # services:
    #     neo4j:
    #         image: neo4j:latest
    #         ports:
    #             - 7474:7474
    #             - 7687:7687
    #         env:
    #             NEO4J_AUTH: neo4j/neo4j

    steps:
      - uses: baptouuuu/setup-neo4j@v1.2.0
        with:
          tag: '3.4' # optional 
      
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19.x'

      - name: Install dependencies
        run: yarn

      - run: cp .env.example .env

      - name: Wait for Neo4j to start
        run: |
            while ! nc -z localhost 7687; do
            sleep 1
            done

      - name: Run tests
        run: yarn run jest test/all.test.ts
